# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Sachin/CommonCode/UDP_LISTENER_LOGGING_CONF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Sachin/CommonCode/UDP_LISTENER_LOGGING_CONF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Sachin/CommonCode/UDP_LISTENER_LOGGING_CONF/CMakeFiles /home/ubuntu/Sachin/CommonCode/UDP_LISTENER_LOGGING_CONF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Sachin/CommonCode/UDP_LISTENER_LOGGING_CONF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UDP_LISTENER

# Build rule for target.
UDP_LISTENER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UDP_LISTENER
.PHONY : UDP_LISTENER

# fast build rule for target.
UDP_LISTENER/fast:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/build
.PHONY : UDP_LISTENER/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/main.cpp.s
.PHONY : main.cpp.s

src/UDP_LISTENER.o: src/UDP_LISTENER.cpp.o

.PHONY : src/UDP_LISTENER.o

# target to build an object file
src/UDP_LISTENER.cpp.o:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/UDP_LISTENER.cpp.o
.PHONY : src/UDP_LISTENER.cpp.o

src/UDP_LISTENER.i: src/UDP_LISTENER.cpp.i

.PHONY : src/UDP_LISTENER.i

# target to preprocess a source file
src/UDP_LISTENER.cpp.i:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/UDP_LISTENER.cpp.i
.PHONY : src/UDP_LISTENER.cpp.i

src/UDP_LISTENER.s: src/UDP_LISTENER.cpp.s

.PHONY : src/UDP_LISTENER.s

# target to generate assembly for a file
src/UDP_LISTENER.cpp.s:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/UDP_LISTENER.cpp.s
.PHONY : src/UDP_LISTENER.cpp.s

src/logging/NanoLog.o: src/logging/NanoLog.cpp.o

.PHONY : src/logging/NanoLog.o

# target to build an object file
src/logging/NanoLog.cpp.o:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/logging/NanoLog.cpp.o
.PHONY : src/logging/NanoLog.cpp.o

src/logging/NanoLog.i: src/logging/NanoLog.cpp.i

.PHONY : src/logging/NanoLog.i

# target to preprocess a source file
src/logging/NanoLog.cpp.i:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/logging/NanoLog.cpp.i
.PHONY : src/logging/NanoLog.cpp.i

src/logging/NanoLog.s: src/logging/NanoLog.cpp.s

.PHONY : src/logging/NanoLog.s

# target to generate assembly for a file
src/logging/NanoLog.cpp.s:
	$(MAKE) -f CMakeFiles/UDP_LISTENER.dir/build.make CMakeFiles/UDP_LISTENER.dir/src/logging/NanoLog.cpp.s
.PHONY : src/logging/NanoLog.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... UDP_LISTENER"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/UDP_LISTENER.o"
	@echo "... src/UDP_LISTENER.i"
	@echo "... src/UDP_LISTENER.s"
	@echo "... src/logging/NanoLog.o"
	@echo "... src/logging/NanoLog.i"
	@echo "... src/logging/NanoLog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

